// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user/register": {
            "post": {
                "description": "創建新用戶帳號",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用戶註冊",
                "parameters": [
                    {
                        "description": "用戶註冊資訊",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UserRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "註冊成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "註冊失敗",
                        "schema": {
                            "$ref": "#/definitions/controllers.UserRegistrationErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/user/test": {
            "get": {
                "description": "測試用戶控制器是否正常運作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "測試用戶控制器",
                "responses": {
                    "200": {
                        "description": "返回成功訊息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gemini/api/image_and_text": {
            "post": {
                "description": "上傳圖片和文字到 Gemini AI 並獲取分析回應",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gemini"
                ],
                "summary": "Gemini AI 圖文分析 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文字訊息",
                        "name": "message",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "圖片檔案",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIErrorResponse"
                        }
                    }
                }
            }
        },
        "/gemini/api/text_only": {
            "post": {
                "description": "傳送訊息到 Gemini AI 並獲取回應",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gemini"
                ],
                "summary": "Gemini AI API",
                "parameters": [
                    {
                        "description": "請求內容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.GeminiAPIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.GeminiAPIErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "無效的輸入格式"
                },
                "error": {
                    "type": "string",
                    "example": "處理請求時發生錯誤"
                }
            }
        },
        "controllers.GeminiAPIRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "你好"
                }
            }
        },
        "controllers.GeminiAPIResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "你好，我是 Gemini AI"
                }
            }
        },
        "controllers.UserRegistrationErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "無效的輸入格式"
                },
                "error": {
                    "type": "string",
                    "example": "處理請求時發生錯誤"
                }
            }
        },
        "controllers.UserRegistrationRequest": {
            "type": "object",
            "required": [
                "userName",
                "userPassword"
            ],
            "properties": {
                "userName": {
                    "type": "string",
                    "example": "admin"
                },
                "userPassword": {
                    "type": "string",
                    "example": "password"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6382",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Menu2What API",
	Description:      "這是一個 Menu2What 的 API 服務",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
